#!/bin/bash

# initialize log file
	echo "" >> serversec_log
	echo "serversec launched - "`date` >> serversec_log
	echo "" >> servesec_log


# IPTABLES #
	# test if iptables is installed, if not, install it and configure it :
	iptables_test=`dpkg -l | grep iptables`
	if [ -z $iptables_test ] ; then
		apt-get install -y iptables
	
		echo "" >> serversec_log
		echo "- iptables has been installed" >> serversec_log
	else
		echo "- iptables is already installed" >> serversec_log
	fi

	# ask the user if he/she wants to update his/her
	# iptables configuration and update it if needed : 
	echo "Do you want to load our configuration for iptables (firewall)?"
	read -p "(yes|no) : " fw_decision
	while [ $fw_decision != "yes" ] && [ $fw_decision != "no" ]
	do 
		echo "please anwser with yes or no"
		read -p "(yes|no) : " fw_decision
	done
	
	if [ $fw_decision = "yes" ] ; then
		cp ./config_files/firewall /etc/init.d/
		echo "- firewall script updated : /etc/init.d/firewall" >> serversec_log
	elif [ $fw_decision = "no" ] ; then
		echo "iptables configuration left untouched"
		echo "- iptables configuration left untouched" >> serversec_log
	fi


# PORTSENTRY #
	# test if portsentry is installed, if not, install it and configure it :
	portsentry_test=`dpkg -l | grep portsentry`
	if [ -z $portsentry_test ] ; then
		apt-get install -y portsentry 
		cp ./config_files/portsentry.conf /etc/portsentry/portsentry.conf
		service portsentry restart
		echo "- portsentry has been installed and configured" >> serversec_log
	else
		echo "- portsentry is already installed" >> serversec_log
	fi


# FAIL2BAN #
	# test if fail2ban is installed, if not, install it and configure it :
	f2b_test=`dpkg -l | grep fail2ban`
	if [ -z $f2b_test ] ; then
		apt-get install -y fail2ban
		cp ./config_files/jail.local /etc/fail2ban/
		service fail2ban restart
		echo "- fail2ban has been installed and configure" >> serversec_log
	else
		echo "- fail2ban is already installed" >> serversec_log
	fi

# SNORT #
	# test if snort is installed, if not, install and configure it : 
	snort=`dpkg -l | grep snort`
	if [ -z $f2b_test ] ; then
		apt-get install -y oinkmaster snort snort-rules-default
		cp ./config_files/oinkmaster.conf /etc/
	
		# download the rules from Emerging Threats servers : 
		oinkmaster -o /etc/snort/rules 
		echo "55 13   * * 6   root    /usr/sbin/oinkmaster -o /etc/snort/rules" >> /etc/crontab
	
		# add the rules to snort config file : 
		echo "#EmergingThreats.net Rules" >> /etc/snort/snort.conf
		for i in `ls /etc/snort/rules/emerging*` 
		do 
			echo "include \$RULE_PATH/"$i >> /etc/snort/snort.conf
		done
	
		/etc/init.d/snort start
	
		echo "- fail2ban has been installed and configure" >> serversec_log
	else
		echo "- fail2ban is already installed" >> serversec_log
	fi

